from data.oneeighty_campaigns_data import oneeighty_campaigns_data
from functions.data_analysis_functions.create_df import create_df
from functions.data_analysis_functions.prepend_report import prepend_report 

create_df(oneeighty_campaigns_data, "oneeighty_campaigns_data")
prepend_report("oneeighty_campaigns_data")
